### ISSUE TITLE
DataBase Schema

### ISSUE THREAD

**Issue by Surya-Mandapati-19** [Raviteja7Lanka/Inventory_Management_SE_Project#3]
I have created a database with 9 tables. Please check it and let me know if any changes need to be done.
[SE databaseSchema.zip](https://github.com/Raviteja7Lanka/Inventory_Management_SE_Project/files/7968127/SE.databaseSchema.zip)

**Comment by smadipad** [comment]
Requested changes have been considered and appropriate solutions have been implemented
