### ISSUE TITLE
As a developer, I should be able to do unit testing on UI components

### ISSUE THREAD

**Issue by smadipad** [Raviteja7Lanka/Inventory_Management_SE_Project#38]

**Comment by Raviteja7Lanka** [comment]
i have implemented united testing for the 6 js modules.


<img width="1198" alt="Screenshot 2022-03-04 at 9 02 54 PM" src="https://user-images.githubusercontent.com/94930984/156863815-fbef974b-cad7-4029-8376-595318ac1f18.png">

**Comment by nithin-meela** [comment]
Looks like the base components passed the unit tests.
