### ISSUE TITLE
As a developer, I should perform cypress tests on UI components

### ISSUE THREAD

**Issue by Raviteja7Lanka** [Raviteja7Lanka/Inventory_Management_SE_Project#41]

**Comment by nithin-meela** [comment]
Successfully executed the test cases for frontend components using Cypress Frame Work 

![image](https://user-images.githubusercontent.com/78529687/156860753-b87a53a0-e62b-40dd-8458-4d4844f4387e.png)

**Comment by Raviteja7Lanka** [comment]
Good work Nithin close the issues and story for the cypress testing.
